;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        nxml-electric-slash
        org-self-insert-command
        shm/del
        shm/delete
        shm/hyphen
        ))

(setq mc/cmds-to-run-once
      '(
        ))
